import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { MainLayout } from '@/components/layout'
import { NextPageWithLayout } from '@/models'

const Home: NextPageWithLayout = () => {
	const router = useRouter()
	function goToDetailPage() {
		router.push({
			pathname: '/posts/[postId]',
			query: {
				postId: 123,
				ref: 'frankie',
			},
		})
	}
	return (
		<>
			<Head>
				<title>Frankie Learn To Code</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>Frankie Hello World</main>
			<Link href='/about'>Go to About</Link>
			<button style={{ cursor: 'pointer' }} onClick={goToDetailPage}>
				Go to Detail page
			</button>
		</>
	)
}

Home.Layout = MainLayout

export default Home
